import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['"Cormorant Garamond"', 'serif'],
        serif: ['"Cormorant Garamond"', 'serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        gold: {
          DEFAULT: "hsl(var(--gold))",
          soft: "hsl(var(--gold-soft))",
          deep: "hsl(var(--gold-deep))",
          light: "hsl(var(--gold-soft))",
          dark: "hsl(var(--gold-deep))",
        },
        burgundy: {
          DEFAULT: "hsl(var(--taupe))",
          light: "hsl(var(--taupe-light))",
        },
        beige: {
          DEFAULT: "hsl(var(--beige))",
          light: "hsl(var(--beige-light))",
          dark: "hsl(var(--beige-dark))",
        },
        champagne: "hsl(var(--champagne))",
        nude: {
          DEFAULT: "hsl(var(--nude))",
          soft: "hsl(var(--nude-soft))",
          deep: "hsl(var(--nude-deep))",
        },
        cream: "hsl(var(--cream))",
        sand: "hsl(var(--sand))",
        rose: "hsl(var(--rose-blush))",
        taupe: {
          DEFAULT: "hsl(var(--taupe))",
          light: "hsl(var(--taupe-light))",
        },
        espresso: "hsl(var(--espresso))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in-up": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { transform: "scale(0.95)", opacity: "0" }, "100%": { transform: "scale(1)", opacity: "1" } },
        "slide-in-left": { "0%": { transform: "translateX(-100%)" }, "100%": { transform: "translateX(0)" } },
        "slide-in-right": { "0%": { transform: "translateX(100%)" }, "100%": { transform: "translateX(0)" } },
        "slide-in-up": { "0%": { transform: "translateY(100%)" }, "100%": { transform: "translateY(0)" } },
        "door-open-left": { "0%": { transform: "perspective(1200px) rotateY(0deg)" }, "100%": { transform: "perspective(1200px) rotateY(-105deg)" } },
        "door-open-right": { "0%": { transform: "perspective(1200px) rotateY(0deg)" }, "100%": { transform: "perspective(1200px) rotateY(105deg)" } },
        "pulse-gold": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.7" } },
        "rotate-slow": { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        "float": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        "typing-dot": { "0%, 60%, 100%": { transform: "translateY(0)", opacity: "0.4" }, "30%": { transform: "translateY(-4px)", opacity: "1" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "bubble-in": { "0%": { opacity: "0", transform: "translateY(8px) scale(0.96)" }, "100%": { opacity: "1", transform: "translateY(0) scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-in-left": "slide-in-left 0.4s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
        "slide-in-up": "slide-in-up 0.4s ease-out forwards",
        "door-open-left": "door-open-left 1s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "door-open-right": "door-open-right 1s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "pulse-gold": "pulse-gold 2s ease-in-out infinite",
        "rotate-slow": "rotate-slow 30s linear infinite",
        "float": "float 3s ease-in-out infinite",
        "typing-dot": "typing-dot 1.4s ease-in-out infinite",
        "shimmer": "shimmer 2.5s linear infinite",
        "bubble-in": "bubble-in 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
